name: PHP Codeception Tests - master

on:
  push:

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: external-calendar
      install-composer: true
      additional-module-id: calendar
      additional-module-composer: true
